"""Generate correctly rounded 64-bit-significand powers of ten from exact rationals.

These constants are mathematical values, not Excel observations or fitted data.
Only nonnegative powers are needed: scale up by multiplication and down by
division. The range includes finite subnormal binary64 for total arithmetic;
the retained Value2 oracle slice admits zero and normal binary64 inputs only.
"""
from fractions import Fraction
from pathlib import Path
import sys

from gen_complex_midpoint_search_20260929 import round_binary


def generate(path):
    lines = ['// Generated by smart-fuzzer/tools/w111/gen_complex_decimal_powers.py.',
             '// Each pair is RN64(10^k) = significand * 2^binary_exponent.',
             '// RN64 is nearest-even rounding to 64 binary significand bits.',
             'pub(super) const POWERS: [(u64, i16); 339] = [']
    for k in range(339):
        value = round_binary(Fraction(10)**k, 64)
        exponent = value.numerator.bit_length() - value.denominator.bit_length() - 63
        significand = value / Fraction(2)**exponent
        assert significand.denominator == 1
        assert 1 << 63 <= significand.numerator < 1 << 64
        lines.append(f'    (0x{significand.numerator:016x}, {exponent}), // 10^{k}')
    lines.append('];')
    path.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(f'{len(lines)-5} mathematically generated powers -> {path}')


if __name__ == '__main__':
    generate(Path(sys.argv[1]))
