"""Generate exact nearest-even binary64-significand powers for the parser model.

These are mathematical constants, not fitted Excel answers. The exponent
carrier is unbounded; '64' means significand precision, not binary64 format.
"""
from fractions import Fraction as F
from pathlib import Path

def pair(k):
    q=F(10)**k;e=q.numerator.bit_length()-q.denominator.bit_length()
    if q<F(2)**e:e-=1
    exponent=e-63;scaled=q/F(2)**exponent
    m,r=divmod(scaled.numerator,scaled.denominator)
    if r*2>scaled.denominator or (r*2==scaled.denominator and m&1):m+=1
    if m==1<<64:m>>=1;exponent+=1
    return m,exponent

exponents=list(range(16))+list(range(16,241,16))+[256]
out=['//! Mathematically generated by smart-fuzzer/tools/w111/gen_decimal_text_powers.py.',
     '//! (64-bit binary significand, power-of-two exponent), nearest-even.']
for sign,name in [(1,'POSITIVE'),(-1,'NEGATIVE')]:
    out.append(f'pub(super) const {name}: [(u64, i16); 32] = [')
    for k in exponents:
        m,e=pair(sign*k);out.append(f'    (0x{m:016x}, {e}), // 10^{sign*k}')
    out.append('];')
Path('crates/oxfunc_core/src/coercion_decimal_powers.rs').write_text('\n'.join(out)+'\n',encoding='utf-8')
