//! Excel-faithful elementary numeric core (W108).
//!
//! # Backend dispatch
//! The public entry points [`excel_exp`], [`excel_log`], and [`excel_log10`]
//! are **bit-exact to 64-bit Microsoft Excel** on `x86_64`: they dispatch to
//! the [`x87`] backend, which executes the legacy Microsoft x87 CRT
//! transcendental sequences (`87tran.asm`, control word `0x133F`, PC=64) that
//! Excel itself runs. On non-`x86_64` targets they fall back to the portable
//! Rust core below (faithful `~0.5` ULP, not bit-exact — Excel-parity is an
//! x87-hardware property; see [`x87`] and the W108 workset).
//!
//! # Portable core (fallback + `expm1`/`log1p`/`sqrt` substrate)
//! [`exp_portable`] / [`log_portable`] are a pure-Rust, zero-dependency port of
//! the glibc-2.29 (Szabolcs Nagy) `__exp` / `__log` routines — the NO-FMA code
//! path, `EXP_TABLE_BITS=7` / `LOG_TABLE_BITS=7`. `excel_expm1` / `excel_log1p`
//! are built on those same argument-reduction + polynomial kernels (NOT glibc's
//! legacy `s_expm1.c` / `s_log1p.c`); `excel_sqrt` is the hardware SQRTSD
//! (SSE2), IEEE-754 correctly-rounded by definition. These have no Excel
//! worksheet counterpart (they are internal composition helpers) and so are not
//! routed through the x87 backend.
//!
//! # Provenance
//! `tables.rs` (`EXP_INVLN2N`, `EXP_TAB`, `LOG_TAB`, …) is machine-generated by
//! [`gen_tables.py`] from the frozen glibc-2.29 C source and MUST NOT be
//! hand-edited — regenerate it if the reference tables ever change. See
//! `docs/worksets/W108_EXCEL_NUMERIC_CORE_AND_FINANCIAL_POWER_EXACTNESS.md`.
//!
//! # Determinism contract
//! * **NO `f64::mul_add` / FMA anywhere.** Every `a*b + c` is two separate IEEE
//!   ops, so the result never depends on whether the target has hardware FMA.
//!   (Rust's default codegen never contracts `a*b + c` into an FMA — that only
//!   happens under explicit `mul_add` or fast-math, neither of which we use.)
//! * No calls into the platform libm. `f64::sqrt` maps to hardware SQRTSD
//!   (SSE2), IEEE-754 correctly-rounded on every target, hence deterministic.
//! * `double_t == f64` here (matching MSVC x64 `FLT_EVAL_METHOD == 0`, the
//!   environment in which the reference was validated).
//!
//! # Accuracy
//! `<= ~0.502 ULP` vs the correctly-rounded result everywhere ("faithful"
//! rounding), i.e. correctly rounded on ~99.5% of inputs. This matches Excel's
//! own ~0.502-ULP bespoke routine on ~99% of inputs; the residual near-midpoint
//! rows (where a faithful core rounds the opposite way) are the tracked W108
//! discrepancy, not a defect.
//!
//! # External validation
//! Bit-identity against the reference C and the full correctly-rounded corpus is
//! proven by the prototype binaries `diff_ref` (bit-for-bit vs the no-FMA
//! glibc-2.29 C output) and `validate_1p` (mpmath prec-240 CR corpus for
//! expm1/log1p), which live with the W108 prototype under
//! `smart-fuzzer/runs/w108a-reference-hunt/`. The in-crate golden-witness test
//! below pins a handful of those correctly-rounded witnesses so any accidental
//! change to the core is caught without depending on the large corpus files.

#![allow(clippy::excessive_precision)]
// Staged for the financial/math kernels (W108 next step). Until those call
// sites land, the `pub(crate)` entry points and their backing tables have no
// in-crate caller, so silence dead_code here rather than crate-wide.
#![allow(dead_code)]

mod tables;
use tables::*;

/// The x87 hardware backend — the only site emitting x87 assembly, used on
/// `x86_64` to reproduce Excel bit-for-bit. See the module docs for provenance.
#[cfg(target_arch = "x86_64")]
mod x87;

/// W109 research surface: raw x87 instruction primitives + `Ext80` extended
/// temporaries for the calculation-graph search tooling. Feature-gated and
/// `x86_64`-only; production kernels never go through here.
#[cfg(all(feature = "research-x87", target_arch = "x86_64"))]
pub mod research;

const EXP_TABLE_BITS: u32 = 7;
const N_EXP: u64 = 1 << EXP_TABLE_BITS; // 128
const LOG_TABLE_BITS: u32 = 7;
const N_LOG: u64 = 1 << LOG_TABLE_BITS; // 128
const OFF: u64 = 0x3fe6000000000000;

#[inline]
fn asuint64(f: f64) -> u64 {
    f.to_bits()
}
#[inline]
fn asdouble(i: u64) -> f64 {
    f64::from_bits(i)
}
#[inline]
fn top12(x: f64) -> u32 {
    (asuint64(x) >> 52) as u32
}
#[inline]
fn top16(x: f64) -> u32 {
    (asuint64(x) >> 48) as u32
}

// exp poly coefficient aliases: poly[5 - EXP_POLY_ORDER=0..], EXP_POLY_ORDER=5.
// C2 = poly[0], C3 = poly[1], C4 = poly[2], C5 = poly[3].
#[inline]
fn c2() -> f64 {
    EXP_POLY[0]
}
#[inline]
fn c3() -> f64 {
    EXP_POLY[1]
}
#[inline]
fn c4() -> f64 {
    EXP_POLY[2]
}
#[inline]
fn c5() -> f64 {
    EXP_POLY[3]
}

/// Handle results that may overflow/underflow (subnormal range). Faithful
/// transcription of glibc `specialcase`, with the errno-only `check_oflow/uflow`
/// tails reduced to identity (they do not change the returned value).
#[inline]
fn specialcase(tmp: f64, mut sbits: u64, ki: u64) -> f64 {
    let scale: f64;
    let mut y: f64;
    if (ki & 0x80000000) == 0 {
        // k > 0, exponent of scale might have overflowed by <= 460.
        sbits = sbits.wrapping_sub(1009u64 << 52);
        scale = asdouble(sbits);
        y = f64::from_bits(0x7f00000000000000) /* 0x1p1009 */ * (scale + scale * tmp);
        return y;
    }
    // k < 0, need special care in the subnormal range.
    sbits = sbits.wrapping_add(1022u64 << 52);
    scale = asdouble(sbits);
    y = scale + scale * tmp;
    if y < 1.0 {
        // Round y to the right precision before scaling into subnormal range
        // to avoid double rounding.
        let hi: f64;
        let mut lo: f64;
        lo = scale - y + scale * tmp;
        hi = 1.0 + y;
        lo = 1.0 - hi + y + lo;
        y = (hi + lo) - 1.0;
        // Avoid -0.0 with downward rounding (WANT_ROUNDING).
        if y == 0.0 {
            y = 0.0;
        }
    }
    y = f64::from_bits(0x0010000000000000) /* 0x1p-1022 */ * y;
    y
}

/// `e^x` — bit-exact to 64-bit Excel's `EXP` on `x86_64` (x87 backend), falling
/// back to the portable faithful core elsewhere. Overflow → `+Inf`, underflow
/// → `+0.0`; the worksheet `#NUM!` mapping is applied by the surface layer.
pub(crate) fn excel_exp(x: f64) -> f64 {
    #[cfg(target_arch = "x86_64")]
    {
        // The x87 chain needs a finite argument; mirror the portable core's
        // non-finite results here.
        if x.is_nan() {
            return f64::NAN;
        }
        if x == f64::INFINITY {
            return f64::INFINITY;
        }
        if x == f64::NEG_INFINITY {
            return 0.0;
        }
        x87::exp(x)
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        exp_portable(x)
    }
}

/// Portable faithful (`~0.502` ULP) double-precision `e^x` — the glibc-2.29
/// no-FMA `__exp` port. The non-`x86_64` fallback for [`excel_exp`], a
/// correctly-rounded reference in tests, and the deterministic substrate the
/// financial family composes against (W108 Bead C, pending its x87 migration).
pub(crate) fn exp_portable(x: f64) -> f64 {
    let mut abstop: u32 = top12(x) & 0x7ff;

    // 0x1p-54 top12, 512.0 top12
    let t_2m54 = top12(f64::from_bits(0x3c90000000000000)); // 0x1p-54
    let t_512 = top12(512.0);
    if abstop.wrapping_sub(t_2m54) >= t_512.wrapping_sub(t_2m54) {
        if abstop.wrapping_sub(t_2m54) >= 0x80000000 {
            // Avoid spurious underflow for tiny x. 0 is common input.
            return 1.0 + x;
        }
        if abstop >= top12(1024.0) {
            if asuint64(x) == asuint64(f64::NEG_INFINITY) {
                return 0.0;
            }
            if abstop >= top12(f64::INFINITY) {
                return 1.0 + x;
            }
            if asuint64(x) >> 63 != 0 {
                return 0.0; // __math_uflow
            } else {
                return f64::INFINITY; // __math_oflow
            }
        }
        // Large x is special cased below.
        abstop = 0;
    }

    // exp(x) = 2^(k/N) * exp(r)
    let z = EXP_INVLN2N * x;
    // !TOINT_INTRINSICS path
    let kd0 = z + EXP_SHIFT;
    let ki = asuint64(kd0);
    let kd = kd0 - EXP_SHIFT;

    let r = x + kd * EXP_NEGLN2HIN + kd * EXP_NEGLN2LON;
    let idx = (2 * (ki % N_EXP)) as usize;
    let top = ki << (52 - EXP_TABLE_BITS);
    let tail = asdouble(EXP_TAB[idx]);
    let sbits = EXP_TAB[idx + 1].wrapping_add(top);
    let r2 = r * r;
    let tmp = tail + r + r2 * (c2() + r * c3()) + r2 * r2 * (c4() + r * c5());
    if abstop == 0 {
        return specialcase(tmp, sbits, ki);
    }
    let scale = asdouble(sbits);
    scale + scale * tmp
}

/// Shared non-normal-domain result for the `fyl2x` logarithms, so `x87::ln`,
/// `x87::log10`, and `x87::log2` all agree with the portable core on `NaN`,
/// `+Inf`, `0`, and negative inputs. Returns `Some(result)` for those; `None`
/// means "compute the logarithm of this finite, positive `x`".
#[cfg(target_arch = "x86_64")]
#[inline]
fn log_domain_guard(x: f64) -> Option<f64> {
    if x.is_nan() {
        return Some(f64::NAN);
    }
    if x == f64::INFINITY {
        return Some(f64::INFINITY);
    }
    if x <= 0.0 {
        // ln(0) = -Inf (incl. -0.0); ln(negative) = NaN. The worksheet #NUM!
        // for x <= 0 is applied by the surface layer / kernel guards.
        return Some(if x == 0.0 {
            f64::NEG_INFINITY
        } else {
            f64::NAN
        });
    }
    None
}

/// `ln(x)` — bit-exact to 64-bit Excel's `LN` on `x86_64` (x87 `fyl2x`), falling
/// back to the portable faithful core elsewhere.
pub(crate) fn excel_log(x: f64) -> f64 {
    #[cfg(target_arch = "x86_64")]
    {
        return log_domain_guard(x).unwrap_or_else(|| x87::ln(x));
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        log_portable(x)
    }
}

/// `log10(x)` — bit-exact to 64-bit Excel's `LOG10` on `x86_64` (x87 `fldlg2` +
/// `fyl2x`), falling back to the platform `log10` elsewhere.
pub(crate) fn excel_log10(x: f64) -> f64 {
    #[cfg(target_arch = "x86_64")]
    {
        return log_domain_guard(x).unwrap_or_else(|| x87::log10(x));
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        x.log10()
    }
}

/// The positive-power staging of Excel's `POWER(x, y)`: `p = exp(y · ln x)` via
/// the x87 `exp`/`ln`, with the product formed as the x87 **double-rounded**
/// `t = RN53(RN64(y · ln x))`. Bit-exact to 64-bit Excel on `x86_64`.
///
/// `base` must be finite and `> 0`, `exp` finite and `> 0`. The caller
/// (`power_fn`) owns the surrounding algorithm: sign of a negative base, the
/// `y < 0` reciprocal via [`excel_x87_recip`], the zero/integer dispatch, and
/// the worksheet error/subnormal publication rules. The returned `p` is the raw
/// positive power and may be `+Inf`, `+0`, or subnormal.
pub(crate) fn excel_pow_positive(base: f64, exp: f64) -> f64 {
    // Excel special-cases exponent 0.5 to the correctly-rounded hardware `sqrt`
    // (SSE2 SQRTSD), NOT `exp(0.5·ln x)` — the latter is 1 ULP off (e.g.
    // POWER(2, 0.5) = √2 exactly). `exp` here is `|y|`, so this also covers the
    // `y = -0.5` case, whose positive power is then reciprocated by the caller.
    // (Live-Excel confirmed 400/400; corrects the reciprocal-staging reference.)
    if exp == 0.5 {
        return base.sqrt();
    }
    #[cfg(target_arch = "x86_64")]
    {
        let ln_base = x87::ln(base);
        let t = x87::mul(exp, ln_base); // RN53(RN64(exp * ln base))
        x87::exp(t)
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        base.powf(exp)
    }
}

/// `RN53(RN64(a + b))` — the x87 double-rounded sum of Excel's legacy
/// x87-compiled function bodies (W109: XNPV's `1 + rate` and running-total
/// accumulation). Bit-exact to 64-bit Excel on `x86_64`; plain `a + b`
/// elsewhere (single-rounded — the documented portable fallback).
pub(crate) fn excel_x87_add(a: f64, b: f64) -> f64 {
    #[cfg(target_arch = "x86_64")]
    {
        x87::add(a, b)
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        a + b
    }
}

/// `RN53(RN64(a / b))` — the x87 double-rounded quotient (W109: XNPV's
/// per-term `value / pow`). Bit-exact to 64-bit Excel on `x86_64`.
pub(crate) fn excel_x87_div(a: f64, b: f64) -> f64 {
    #[cfg(target_arch = "x86_64")]
    {
        x87::div(a, b)
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        a / b
    }
}

/// `RN53(RN64(1.0 / x))` — the x87 double-rounded reciprocal Excel uses to stage
/// `POWER(x, y)` for `y < 0` (positive power, stored to `binary64`, then one
/// reciprocal). Bit-exact to 64-bit Excel on `x86_64`.
pub(crate) fn excel_x87_recip(x: f64) -> f64 {
    #[cfg(target_arch = "x86_64")]
    {
        x87::recip(x)
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        1.0 / x
    }
}

/// Portable faithful (`~0.507` ULP) double-precision `ln(x)` — the glibc-2.29
/// no-FMA `__log` port. The non-`x86_64` fallback for [`excel_log`], a
/// correctly-rounded reference in tests, and the deterministic substrate the
/// financial family composes against (W108 Bead C, pending its x87 migration).
pub(crate) fn log_portable(x: f64) -> f64 {
    let ix = asuint64(x);
    let top = top16(x);

    // Close-to-1.0 fast path.
    let lo_b = asuint64(1.0 - f64::from_bits(0x3fb0000000000000)); // 1.0 - 0x1p-4
    let hi_b = asuint64(1.0 + f64::from_bits(0x3fb0900000000000)); // 1.0 + 0x1.09p-4
    if ix.wrapping_sub(lo_b) < hi_b.wrapping_sub(lo_b) {
        // Fix sign of zero with downward rounding when x==1.
        if ix == asuint64(1.0) {
            return 0.0;
        }
        let r = x - 1.0;
        let r2 = r * r;
        let r3 = r * r2;
        let b = &LOG_POLY1;
        let mut y = r3
            * (b[1]
                + r * b[2]
                + r2 * b[3]
                + r3 * (b[4]
                    + r * b[5]
                    + r2 * b[6]
                    + r3 * (b[7] + r * b[8] + r2 * b[9] + r3 * b[10])));
        let w = r * f64::from_bits(0x41a0000000000000); // 0x1p27
        let rhi = r + w - w;
        let rlo = r - rhi;
        let w2 = rhi * rhi * b[0]; // b[0] == -0.5
        let hi = r + w2;
        let mut lo = r - hi + w2;
        lo += b[0] * rlo * (rhi + r);
        y += lo;
        y += hi;
        return y;
    }

    let mut ix = ix;
    if top.wrapping_sub(0x0010) >= 0x7ff0 - 0x0010 {
        // x < 0x1p-1022 or inf or nan.
        if ix.wrapping_mul(2) == 0 {
            return f64::NEG_INFINITY; // __math_divzero
        }
        if ix == asuint64(f64::INFINITY) {
            return x; // log(inf) == inf
        }
        if (top & 0x8000) != 0 || (top & 0x7ff0) == 0x7ff0 {
            return (x - x) / (x - x); // __math_invalid -> NaN
        }
        // subnormal, normalize
        ix = asuint64(x * f64::from_bits(0x4330000000000000)); // 0x1p52
        ix = ix.wrapping_sub(52u64 << 52);
    }

    let (hi, lo_rest) = log_general_hi_lo(ix);
    hi + lo_rest
}

/// Internal: the main `__log` table path, returning the result as an unrounded
/// (hi, lo_rest) pair such that `log(x) == hi + lo_rest` (before final rounding).
/// `ix` is `asuint64(x)` for a NORMAL, positive x already outside the close-to-1
/// window (subnormals must be pre-normalized by the caller as in `excel_log`).
/// Exposing the split lets `excel_log1p` inject the `1+x` compensation term
/// into `lo_rest` and round only once.
#[inline]
fn log_general_hi_lo(ix: u64) -> (f64, f64) {
    let tmp = ix.wrapping_sub(OFF);
    let i = ((tmp >> (52 - LOG_TABLE_BITS)) % N_LOG) as usize;
    let k = (tmp as i64) >> 52; // arithmetic shift
    let iz = ix.wrapping_sub(tmp & (0xfffu64 << 52));
    let (invc, logc) = LOG_TAB[i];
    let z = asdouble(iz);

    // no-FMA path: r = (z - chi - clo) * invc
    let (chi, clo) = LOG_TAB2[i];
    let r = (z - chi - clo) * invc;
    let kd = k as f64;

    let w = kd * LOG_LN2HI + logc;
    let hi = w + r;
    let lo = w - hi + r + kd * LOG_LN2LO;

    let r2 = r * r;
    let a = &LOG_POLY;
    // lo_rest = lo + polynomial (everything except the dominant `hi` term)
    let lo_rest = lo + r2 * a[0] + r * r2 * (a[1] + r * a[2] + r2 * (a[3] + r * a[4]));
    (hi, lo_rest)
}

// ============================================================================
// expm1 — built on excel_exp's argument reduction + polynomial, NOT glibc's
// legacy s_expm1.c. For non-tiny x we reproduce exp's decomposition
//   exp(x) = scale * (1 + tmp),   scale = 2^(k/N),   tmp = tail + poly(r)
// and reconstruct expm1(x) = (scale - 1) + scale*tmp with a compensated
// subtraction so the leading digits are not lost. For small |x| (k == 0) we
// evaluate the exp polynomial directly (expm1 ~ r + poly), and for tiny |x| we
// return x (expm1(x) -> x with no representable correction).
// ============================================================================

/// e^x - 1 — faithful (~0.5 ULP) deterministic double-precision expm1.
pub(crate) fn excel_expm1(x: f64) -> f64 {
    let ix = asuint64(x);
    let abstop = top12(x) & 0x7ff;

    // |x| < 0x1p-53: expm1(x) == x to nearest (including +-0 and subnormals),
    // because the next term x^2/2 is below 0.5 ULP of x.
    if abstop < top12(f64::from_bits(0x3ca0000000000000)) {
        // 0x1p-53
        return x;
    }

    // Special / out-of-range handling.
    // top12(0x1p6)=... use |x| >= 0x1.63108c75a1937p+9 ~ 708 overflow; and
    // x <= -0x1.2b708872320e2p+5 (~ -37.4) => expm1 == -1 to nearest.
    if abstop >= top12(708.0_f64) {
        // near the exp overflow / large-magnitude regime, or inf/nan
        if abstop >= 0x7ff {
            // inf or nan
            if ix == asuint64(f64::NEG_INFINITY) {
                return -1.0;
            }
            // +inf -> +inf ; nan -> nan (x propagates, +1 keeps nan)
            return x + x;
        }
        if x > 0.0 {
            // exp overflows -> expm1 overflows to +inf
            return f64::INFINITY;
        }
        // very negative: expm1(x) == -1 (exp(x) underflows below 0.5 ULP of 1)
        return -1.0;
    }
    // For x <= about -37 (still finite, abstop below 708 top12 only if |x|<512),
    // handle the "expm1 == -1" saturation explicitly: exp(x) < 2^-54 => e^x-1
    // rounds to -1.
    if x < -37.0 {
        return -1.0;
    }

    // ---- exp's argument reduction (no-FMA path, matches excel_exp) ----
    let z = EXP_INVLN2N * x;
    let kd0 = z + EXP_SHIFT;
    let ki = asuint64(kd0);
    let kd = kd0 - EXP_SHIFT;
    let r = x + kd * EXP_NEGLN2HIN + kd * EXP_NEGLN2LON;
    let idx = (2 * (ki % N_EXP)) as usize;
    let top = ki << (52 - EXP_TABLE_BITS);
    let tail = asdouble(EXP_TAB[idx]);
    let sbits = EXP_TAB[idx + 1].wrapping_add(top);
    let r2 = r * r;
    // tmp such that exp(x) = scale * (1 + tmp)
    let tmp = tail + r + r2 * (c2() + r * c3()) + r2 * r2 * (c4() + r * c5());
    let scale = asdouble(sbits);

    // expm1(x) = scale*(1+tmp) - 1 = (scale - 1) + scale*tmp
    // Compute (scale - 1) with a compensated split so we keep the low bits when
    // scale is close to 1 (small k). Use a two-sum of (scale - 1).
    let sm1 = scale - 1.0;
    // exact error of (scale - 1): scale - 1 is exact when |k| small... not
    // always. Recover the rounding remainder of scale-1 via Dekker two-sum with
    // the known operands (scale, -1.0).
    // two_sum(scale, -1.0): s = scale + (-1); bb = s - scale; err = (scale-(s-bb)) + (-1 - bb)
    let s = sm1;
    let bb = s - scale;
    let err = (scale - (s - bb)) + (-1.0 - bb);
    // result = s + (scale*tmp + err), added in increasing-magnitude order.
    let y = scale * tmp + err;
    s + y
}

// ============================================================================
// log1p — built on excel_log's poly1 double-double kernel (for small |x|) and
// the main __log table path (for the rest), NOT glibc's legacy s_log1p.c.
// For the rest we form 1+x as a compensated (hi, lo) pair so no precision is
// lost, take log(hi) via the main kernel, and add the exact correction lo/hi.
// ============================================================================

/// log(1 + x) — faithful (~0.5 ULP) deterministic double-precision log1p.
pub(crate) fn excel_log1p(x: f64) -> f64 {
    let ix = asuint64(x);
    let top = top16(x);

    // ---- edge cases ----
    // log1p(0) = +0 ; log1p(-0) = -0 (preserve sign of zero).
    if x == 0.0 {
        return x;
    }
    if x.is_nan() {
        return x + x;
    }
    if x == f64::INFINITY {
        return f64::INFINITY;
    }
    // x < -1 -> NaN ; x == -1 -> -inf.
    if x < -1.0 {
        return (x - x) / (x - x); // NaN
    }
    if x == -1.0 {
        return f64::NEG_INFINITY;
    }

    // ---- small |x|: direct poly1 double-double kernel with f = x ----
    // The __log close-to-1 branch computes log(1+r) with r = (input) - 1. Here
    // the input IS 1+x, so r = x exactly (no rounding), giving a cancellation-
    // free log1p for |x| in [-0x1p-4, 0x1.09p-4].
    // Bounds mirror excel_log's close-to-1 window, expressed on x directly.
    let x_lo = -f64::from_bits(0x3fb0000000000000); // -0x1p-4
    let x_hi = f64::from_bits(0x3fb0900000000000); //  0x1.09p-4
    if x >= x_lo && x <= x_hi {
        let r = x;
        let r2 = r * r;
        let r3 = r * r2;
        let b = &LOG_POLY1;
        let mut y = r3
            * (b[1]
                + r * b[2]
                + r2 * b[3]
                + r3 * (b[4]
                    + r * b[5]
                    + r2 * b[6]
                    + r3 * (b[7] + r * b[8] + r2 * b[9] + r3 * b[10])));
        let w = r * f64::from_bits(0x41a0000000000000); // 0x1p27
        let rhi = r + w - w;
        let rlo = r - rhi;
        let w2 = rhi * rhi * b[0]; // b[0] == -0.5
        let hi = r + w2;
        let mut lo = r - hi + w2;
        lo += b[0] * rlo * (rhi + r);
        y += lo;
        y += hi;
        return y;
    }

    // ---- general path: form 1+x as compensated (uhi, ulo), then
    //      log1p(x) = log(uhi) + ulo/uhi. ----
    let _ = (ix, top);
    // two_sum(1.0, x) (Knuth, no ordering assumption) so uhi + ulo == 1 + x
    // EXACTLY. ulo captures the bits of x lost when rounding 1+x.
    let uhi = 1.0 + x;
    let bv = uhi - 1.0;
    let ulo = (1.0 - (uhi - bv)) + (x - bv);

    // uhi is in (0, 2) and normal here (|x| may be up to 1e6). If uhi happens to
    // land in the close-to-1 window we still get a correct result via the table
    // kernel below (poly1 already handled small x). Get log(uhi) as (hi, lo_rest)
    // and inject the correction ulo/uhi BEFORE the single final rounding:
    //   log(1+x) = log(uhi + ulo) = log(uhi) + ulo/uhi  (d log/du = 1/u).
    let (hi, mut lo_rest) = log_general_hi_lo(asuint64(uhi));
    lo_rest += ulo / uhi;
    hi + lo_rest
}

/// sqrt(x) — IEEE-754 correctly-rounded, deterministic (hardware SQRTSD).
#[inline]
pub(crate) fn excel_sqrt(x: f64) -> f64 {
    x.sqrt()
}

#[cfg(test)]
mod tests {
    use super::*;

    // Golden (x_bits, cr_bits) pulled from the W108-A corpus. These pin the
    // *portable* faithful core (`exp_portable`/`log_portable` and the
    // expm1/log1p/sqrt kernels) to the correctly-rounded value. Excel-parity of
    // the x87 EXP/LN backend is covered separately by
    // `x87::tests::matches_live_excel_bit_for_bit`.
    const GOLDEN: &[(&str, u64, u64)] = &[
        ("EXP", 0xc034000000000000, 0x3e21b48655f37267),
        ("EXP", 0xc034000000000010, 0x3e21b48655f3714c),
        ("EXP", 0xc033ffffffffffef, 0x3e21b48655f37394),
        ("EXP", 0xc034000000000029, 0x3e21b48655f36f91),
        ("LN", 0x3fe0000000000000, 0xbfe62e42fefa39ef),
        ("LN", 0x3fe000000000000e, 0xbfe62e42fefa39d3),
        ("LN", 0x3fe0000000000015, 0xbfe62e42fefa39c5),
        ("LN", 0x3fe02f71aaff02f7, 0xbfe5cfeb44399090),
        ("SQRT", 0x3eb0c6f7a0b5ed8d, 0x3f50624dd2f1a9fc),
        ("SQRT", 0x3eb0c6f7a0b5ed98, 0x3f50624dd2f1aa01),
        ("SQRT", 0x3eb0c6f7a0b5edad, 0x3f50624dd2f1aa0b),
        ("SQRT", 0x3eb0c6f7a0b5eda4, 0x3f50624dd2f1aa07),
        // expm1/log1p CR goldens (mpmath prec 240)
        ("EXPM1", 0x3fda53e707e19ead, 0x3fe048c94c677b63),
        ("EXPM1", 0x3fdb3061c79b5d80, 0x3fe0f03fea9c350d),
        ("EXPM1", 0x3fdc0cdc87551c53, 0x3fe199fb57f320f9),
        ("EXPM1", 0x3fdce957470edb26, 0x3fe2460372d441c9),
        ("LOG1P", 0xbf7e4c6824a105fb, 0xbf7e693c89601f4e),
        ("LOG1P", 0x3f7ab037b0fcada5, 0x3f7a9a0e2db5905f),
        ("LOG1P", 0xbf946ef81ba4d29a, 0xbf94a3dd68efff1c),
        ("LOG1P", 0xbf9462c5719f45e5, 0xbf94976b3dc504e8),
    ];

    #[test]
    fn golden_matches_cr() {
        for &(f, xb, crb) in GOLDEN {
            let x = f64::from_bits(xb);
            let got = match f {
                "EXP" => exp_portable(x),
                "LN" => log_portable(x),
                "SQRT" => excel_sqrt(x),
                "EXPM1" => excel_expm1(x),
                "LOG1P" => excel_log1p(x),
                _ => unreachable!(),
            }
            .to_bits();
            assert_eq!(
                got, crb,
                "{} x=0x{:016x}: got 0x{:016x} want 0x{:016x}",
                f, xb, got, crb
            );
        }
    }

    #[test]
    fn expm1_edge_cases() {
        assert_eq!(excel_expm1(0.0).to_bits(), 0.0f64.to_bits()); // +0
        assert_eq!(excel_expm1(-0.0).to_bits(), (-0.0f64).to_bits()); // -0 preserved
        assert_eq!(excel_expm1(f64::NEG_INFINITY), -1.0);
        assert_eq!(excel_expm1(f64::INFINITY), f64::INFINITY);
        assert!(excel_expm1(f64::NAN).is_nan());
        assert_eq!(excel_expm1(1000.0), f64::INFINITY); // overflow
        assert_eq!(excel_expm1(-1000.0), -1.0); // saturates to -1
        assert_eq!(excel_expm1(-50.0), -1.0); // exp(-50) below 0.5 ULP of 1
        // tiny x: expm1(x) == x
        let tiny = f64::from_bits(0x3c80000000000000); // 0x1p-55
        assert_eq!(excel_expm1(tiny).to_bits(), tiny.to_bits());
        // expm1(1): the correctly-rounded double is 0x3ffb7e151628aed3 (mpmath).
        // Note this is NOT (E - 1.0) = 0x3ffb7e151628aed2, which is 1 ULP low —
        // exactly the cancellation expm1 exists to avoid.
        assert_eq!(excel_expm1(1.0).to_bits(), 0x3ffb7e151628aed3);
    }

    #[test]
    fn log1p_edge_cases() {
        assert_eq!(excel_log1p(0.0).to_bits(), 0.0f64.to_bits()); // +0
        assert_eq!(excel_log1p(-0.0).to_bits(), (-0.0f64).to_bits()); // -0 preserved
        assert_eq!(excel_log1p(-1.0), f64::NEG_INFINITY);
        assert!(excel_log1p(-1.5).is_nan()); // x < -1
        assert!(excel_log1p(-2.0).is_nan());
        assert_eq!(excel_log1p(f64::INFINITY), f64::INFINITY);
        assert!(excel_log1p(f64::NAN).is_nan());
        // consistency with log: log1p(x) == log(1+x) where 1+x is exact
        assert_eq!(excel_log1p(1.0).to_bits(), excel_log(2.0).to_bits());
        assert_eq!(excel_log1p(7.0).to_bits(), excel_log(8.0).to_bits());
    }

    #[test]
    fn edge_cases() {
        assert_eq!(excel_exp(0.0).to_bits(), 1.0f64.to_bits());
        assert_eq!(excel_exp(-0.0).to_bits(), 1.0f64.to_bits());
        assert_eq!(excel_log(1.0).to_bits(), 0.0f64.to_bits()); // +0.0, not -0.0
        assert!(excel_log(-1.0).is_nan());
        assert_eq!(excel_log(f64::INFINITY), f64::INFINITY);
        assert_eq!(excel_log(0.0), f64::NEG_INFINITY);
        assert_eq!(excel_exp(f64::NEG_INFINITY), 0.0);
        assert_eq!(excel_exp(710.0), f64::INFINITY); // overflow
        assert_eq!(excel_exp(-746.0), 0.0); // underflow to 0
        assert!(excel_exp(f64::NAN).is_nan());
    }
}
