use oxfunc_core::xll_export_specs::{OXFUNC_XLL_EXPORT_SPECS, XllEntryKind, XllULiftPolicy};
use std::env;
use std::fs;
use std::path::PathBuf;

fn assert_rust_ident(name: &str) {
    let mut chars = name.chars();
    let first = chars.next().unwrap_or('_');
    if !(first == '_' || first.is_ascii_alphabetic()) {
        panic!("export_name is not a valid Rust identifier: {name}");
    }
    if !chars.all(|c| c == '_' || c.is_ascii_alphanumeric()) {
        panic!("export_name is not a valid Rust identifier: {name}");
    }
}

fn emit_generated() -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from oxfunc_core::xll_export_specs\n");
    out.push_str("// Do not edit by hand.\n\n");

    for row in OXFUNC_XLL_EXPORT_SPECS {
        assert_rust_ident(row.export_name);
        let const_name = format!("SPEC_{}", row.export_name);
        let registration_block = format!(
            "registration: RegistrationSpec {{ export_name: \"{export_name}\", type_text: \"{type_text}\", function_name: \"{worksheet_name}\", arg_names: \"{arg_names}\" }}",
            export_name = row.export_name,
            type_text = row.type_text,
            worksheet_name = row.worksheet_name,
            arg_names = row.arg_names
        );
        match row.entry_kind {
            XllEntryKind::UUnary => {
                let lift = match row.u_lift_policy {
                    Some(XllULiftPolicy::ScalarOnly) => "ULiftPolicy::ScalarOnly",
                    Some(XllULiftPolicy::UnaryScalarOrArrayElementwise) => {
                        "ULiftPolicy::UnaryScalarOrArrayElementwise"
                    }
                    None => panic!("missing u_lift_policy for {}", row.export_name),
                };
                out.push_str(&format!(
                    "const {const_name}: UExportSpec = UExportSpec {{ function_id: \"{function_id}\", {registration_block}, lift_policy: {lift} }};\n",
                    const_name = const_name,
                    function_id = row.function_id,
                    registration_block = registration_block,
                    lift = lift
                ));
                out.push_str(&format!(
                    "#[unsafe(no_mangle)]\npub extern \"system\" fn {export_name}(arg: *mut XLOPER12) -> *mut XLOPER12 {{\n    eval_u_export({const_name}, arg)\n}}\n\n",
                    export_name = row.export_name,
                    const_name = const_name
                ));
            }
            XllEntryKind::QUnaryNumber => {
                out.push_str(&format!(
                    "const {const_name}: QUnaryNumberExportSpec = QUnaryNumberExportSpec {{ function_id: \"{function_id}\", {registration_block} }};\n",
                    const_name = const_name,
                    function_id = row.function_id,
                    registration_block = registration_block
                ));
                out.push_str(&format!(
                    "#[unsafe(no_mangle)]\npub extern \"system\" fn {export_name}(value: f64) -> f64 {{\n    eval_q_unary_number_export({const_name}, value)\n}}\n\n",
                    export_name = row.export_name,
                    const_name = const_name
                ));
            }
            XllEntryKind::QNullaryNumber => {
                out.push_str(&format!(
                    "const {const_name}: QNullaryNumberExportSpec = QNullaryNumberExportSpec {{ function_id: \"{function_id}\", {registration_block} }};\n",
                    const_name = const_name,
                    function_id = row.function_id,
                    registration_block = registration_block
                ));
                out.push_str(&format!(
                    "#[unsafe(no_mangle)]\npub extern \"system\" fn {export_name}() -> f64 {{\n    eval_q_nullary_number_export({const_name})\n}}\n\n",
                    export_name = row.export_name,
                    const_name = const_name
                ));
            }
        }
    }

    out.push_str(&format!(
        "const GENERATED_REGISTRATION_SPECS: [RegistrationSpec; {}] = [\n",
        OXFUNC_XLL_EXPORT_SPECS.len()
    ));
    for row in OXFUNC_XLL_EXPORT_SPECS {
        let const_name = format!("SPEC_{}", row.export_name);
        out.push_str(&format!("    {const_name}.registration,\n"));
    }
    out.push_str("];\n");

    out
}

fn main() {
    // Keep regeneration aligned when core source-of-truth changes.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let core_specs = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("crates")
        .join("oxfunc_core")
        .join("src")
        .join("xll_export_specs.rs");
    let core_surface_dispatch = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("crates")
        .join("oxfunc_core")
        .join("src")
        .join("functions")
        .join("surface_dispatch.rs");
    println!("cargo:rerun-if-changed={}", core_specs.display());
    println!(
        "cargo:rerun-if-changed={}",
        core_surface_dispatch.display()
    );

    let generated = emit_generated();
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("xll_generated_exports.rs");
    fs::write(&out_file, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_file.display()));
}
